blank_issues_enabled: true

contact_links:
  - name: 💬 WebUI Community Support
    url: https://github.com/webui-dev/webui/discussions
    about: Please can ask and answer questions about WebUI here.
