name: macOS

on:
  workflow_call:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: vwebui
      - name: Setup V
        run: |
          curl -Lo v_macos_arm64.zip https://github.com/vlang/v/releases/latest/download/v_macos_arm64.zip
          unzip -o v_macos_arm64.zip
          mv v ~/v && ~/v/v symlink
      - name: Setup WebUI library
        run: |
          mkdir -p ~/.vmodules && mv vwebui ~/.vmodules/vwebui
          ~/.vmodules/vwebui/setup.vsh
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  build-examples:
    needs: setup
    runs-on: macos-latest
    strategy:
      matrix:
        cc: [clang]
        optimization: ['', '-W -cstrict']
      fail-fast: false
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }} ${{ matrix.optimization }}
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && v -showcc self && v doctor
      - name: Build
        run: |
          for path in $(find ~/.vmodules/vwebui/examples/* -maxdepth 0); do
            if [[ -d "$path" || "$path" == *.v ]]; then
              cmd="v $path"
            fi
            echo "$cmd"
            eval "$cmd"
          done
